// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvkeiqhcsoxiqkcetgvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52a2VpcWhjc294aXFrY2V0Z3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTc0NjIsImV4cCI6MjA2MTgzMzQ2Mn0.Mo5fhApCPhvQTCKKTaw0lmmXFtYxDyF8sSpig07RZCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);